name: 🚀 Deploy Firebase

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🔑 Injecter les clés
        run: |
          sed -i "s/REMPLACE-PAR-TA-CLE-BREVO/${{ secrets.BREVO_KEY }}/g" index.html
          sed -i "s/REMPLACE-PAR-TA-CLE-WEB3FORMS/${{ secrets.WEB3FORMS_KEY }}/g" index.html
          sed -i "s/REMPLACE-PAR-TON-EMAIL/${{ secrets.BREVO_SENDER }}/g" index.html
          sed -i "s|REMPLACE-PAR-TON-PSEUDO|${{ secrets.GITHUB_PSEUDO }}|g" index.html

      - name: 📦 Install Firebase tools
        run: npm install -g firebase-tools

      - name: 🚀 Deploy
        run: firebase deploy --only hosting --project "${{ secrets.FIREBASE_PROJECT_ID }}" --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
